version: '0.0.1'
services:
  db:
    image: postgres:15
    container_name: organize-simple-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: organize-simple
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5466:5432'
volumes:
  db_data:
    name: organize-simple-data